# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 https://botev.github.io/

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             ''

title:               Alex Botev

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# FOUT, FOIT, FOFT removal for when javascript is on - https://github.com/qwtel/hydejack/issues/14
fout_removal:        true

# Whether to add about at the end of each post
per_post_about:      false


# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Posts and thoughts on topics in Machine Learning.

# The tags listed as entries in the sidebar
sidebar_tags:        [autodiff]

# Fallback image and color if not overwritten for tag or post
# image:               /hydejack/public/img/nap.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Aleksandar Botev'

  # This photo will be used in the about section
  photo:             /public/img/pic43.jpg
  photo2x:           /public/img/pic432x.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             I'm a graduate student in Machine Learning at [UCL](http://www.cs.ucl.ac.uk).
    I did an undergraduate degree in Computer Science at [University of Southampton](http://www.ecs.soton.ac.uk/)
    followed by a Master of Research degree in [UCL](http://www.cs.ucl.ac.uk) which lead to my PhD.
    I'm leading the tutorial on Graphical Models (GM08) for the Masters students in our departament.
    My supervisor is David Barber, who also has a blog which you can read [here](http://davidbarber.github.io/).


    My interests are briefly in anything that we deem "interesintg" in the
    borader area of Artificial Intelligence. This spans from Generative Models, Neural Networks and Optimization
    to [autodiff](https://en.wikipedia.org/wiki/Automatic_differentiation) tools and
    hardware for Machine Learning. I'm also in love with [Rust](https://www.rust-lang.org) and hope in the future to be able
    to use it more for my own research.

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    # facebook:        _username_
    # twitter:         _username_
    # google:          _number_
    # vk:              _username_
    # youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    reddit:          alexbotev
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:          botev
    stackoverflow:   680794/alex-botev
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    linkedin:        aleksandarbotev
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
google_analytics_id: 'UA-84025722-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
